version: 2
sources:
  - name: adventure_works
    database: fea24_9
    schema: raw_adventure_works
    freshness:
      warn_after: { count: 18250, period: day }
    loaded_at_field: cast(modifieddate as timestamp)
    tables:
      - name: address
      - name: businessentitycontact
      - name: countryregion
      - name: creditcard
      - name: customer
      - name: person
      - name: product
      - name: productcategory
      - name: productsubcategory
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesreason
      - name: stateprovince
      - name: store
