version: 2
sources:
  - name: adventure_works
    database: fea24_9
    schema: raw_adventure_works
    freshness:
      warn_after: { count: 18250, period: day }
    loaded_at_field: cast(modifieddate as timestamp)
    tables:
      - name: address
        columns:
          - name: addressid
            data_tests:
              - unique
              - not_null
      - name: businessentitycontact
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - businessentityid
                - personid
                - contacttypeid
      - name: countryregion
        columns:
          - name: countryregioncode
            data_tests:
              - unique
              - not_null
      - name: creditcard
        columns:
          - name: creditcardid
            data_tests:
              - unique
              - not_null                  
      - name: customer
        columns:
          - name: customerid
            data_tests:
              - unique
              - not_null
      - name: person
        columns:
          - name: businessentityid
            data_tests:
              - unique
              - not_null
      - name: product
        columns:
          - name: productid
            data_tests:
              - unique
              - not_null
      - name: productcategory
        columns:
          - name: productcategoryid
            data_tests:
              - unique
              - not_null
      - name: productsubcategory
        columns:
          - name: productsubcategoryid
            data_tests:
              - unique
              - not_null
      - name: salesorderdetail
        columns:
          - name: salesorderdetailid
            data_tests:
              - unique
              - not_null
      - name: salesorderheader
        columns:
          - name: salesorderid
            data_tests:
              - unique
              - not_null
      - name: salesorderheadersalesreason
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - salesorderid
                - salesreasonid
      - name: salesreason
        columns:
          - name: salesreasonid
            data_tests:
              - unique
              - not_null
      - name: stateprovince
        columns:
          - name: stateprovinceid
            data_tests:
              - unique
              - not_null
      - name: store
        columns:
          - name: businessentityid
            data_tests:
              - unique
              - not_null
